# This Docker Compose file sets up a multi-container application with three services: cardinal, db, and nginx.
#
# Services:
# 1. cardinal:
#    - Builds the image from the Dockerfile located in the ./cardinal directory.
#    - Sets an environment variable CARDINAL_DOCKER to 1.
#    - Maps port 19999 on the host to port 19999 in the container.
#    - Mounts the configuration file ./conf/Cardinal.toml to /Cardinal/conf/Cardinal.toml in the container.
#    - Configures logging with a maximum size of 200k and a maximum of 10 log files.
#    - Always restarts the container if it stops.
#    - Depends on the db service to be started first.
#
# 2. db:
#    - Uses the mysql:8.0.21 image.
#    - Mounts the ./Cardinal_database directory to /var/lib/mysql in the container to persist database data.
#    - Configures logging with a maximum size of 200k and a maximum of 10 log files.
#    - Always restarts the container if it stops.
#    - Sets environment variables for MySQL root password, database name, user, and password.
#    - Runs the MySQL server with UTF-8 MB4 character set and collation.
#
# 3. web:
#    - Builds the image from the Dockerfile located in the ./web directory.
#    - Maps port 8087 on the host to port 80 in the container.
#    - Mounts the configuration file ./web/nginx.conf to /etc/nginx/conf.d/default.conf in the container.
#    - Configures logging with a maximum size of 200k and a maximum of 10 log files.
#    - Always restarts the container if it stops.
services:
  cardinal:
    build:
      context: ./cardinal
    environment:
      CARDINAL_DOCKER: 1
    volumes:
      - ./conf/Cardinal.toml:/Cardinal/conf/Cardinal.toml
      - ./checker/:/checker/
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.0.21
    volumes:
      - ./Cardinal_database:/var/lib/mysql
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Cardinal
      MYSQL_DATABASE: Cardinal
      MYSQL_USER: Cardinal
      MYSQL_PASSWORD: Cardinal
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  web:
    build:
      context: ./web
    ports:
      - 8087:80
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
